version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expõe a porta 27017 para o host
    networks:
      - blocker_network
    volumes: 
      - mongodb_data:/data/db  # Mantém os dados do MongoDB persistentes

networks:
  blocker_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
